### ISSUE TITLE
Added Alex's bio

### ISSUE THREAD

**Issue by alex-maletskyi** [HYF-Class21/workflows-group4-intro#10] opened 2023-03-28 12:59 UTC
- Setup: GitHub
  - [x] created this issue
  - [x] assigned myself
  - [x] moved the issue to the project board
- Setup: local
  - [x] pulled the most recent code from `main`/`master`
  - [x] created a new branch for my introduction
- Writing the content:
  - [x] added my intro file in `/group4` according to group conventions
  - [x] linked to my file from `/README.md` according to group conventions
- Before pushing my branch:
  - [x] formatted the code
  - [x] fixed all spelling mistakes and added new words to the dictionary
  - [x] fixed all linting mistakes
- After pushing my branch:
  - [x] created a new PR linked to this issue
  - [x] make sure all of the checks passed
  - [x] #11

**Comment by sammou00** [comment] 2023-03-29 16:09
@alex-maletskyi  Why the issue is still opens and you merged your `PR`

**Comment by alex-maletskyi** [comment] 2023-03-29 19:23
During the class on Sunday I started with pushing my code and making the pull request and forgot to create the issue first

**Closed as completed** 2023-03-29 19:26 UTC
Labels: md
